# just for testing notifications from agrocd
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: default
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
